version: "3.7"
services:
  helpaneighbor:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/helpaneighbor
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:12-master
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: helpaneighbor
      POSTGRES_PASSWORD: dont-hack-me
